# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

strategy:
  matrix:
    windows_node_8_x:
      vmImage: 'vs2017-win2017'
      node_version: 8.x
    windows_node_10_x:
      vmImage: 'vs2017-win2017'
      node_version: 10.x
    linux_node_8_x:
      vmImage: 'ubuntu-16.04'
      node_version: 8.x
    linux_node_10_x:
      vmImage: 'ubuntu-16.04'
      node_version: 10.x

pool:
  vmImage: $(vmImage)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- script: npm link --loglevel error; npm run build
  displayName: 'Build'

- script: npm install -g rimraf; mkdir demo; cd demo
  displayName: 'Setup Full-Cycle Test'
    
- script: ipack new vue; ipack; ipack -dx
  displayName: 'Full-Cycle Test: vue'

- script: rimraf ./*; ipack new react; ipack; ipack -dx
  displayName: 'Full-Cycle Test: react'

- script: rimraf ./*; ipack new preact; ipack; ipack -dx
  displayName: 'Full-Cycle Test: preact'

- script: rimraf ./*; ipack new inferno; ipack; ipack -dx
  displayName: 'Full-Cycle Test: inferno'

- script: rimraf ./*; ipack new hyperapp; ipack; ipack -dx
  displayName: 'Full-Cycle Test: hyperapp'
